name: CI

on:
  pull_request:

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query ($owner: String!, $name: String!, $label: String!) {
              repository(owner: $owner, name: $name) {
                issues(first: 100, labels: [$label], states: OPEN) {
                  totalCount
                  nodes {
                    id
                    title
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              label: 'root'
            }
            const result = await github.graphql(query, variables)
            console.log(result)
