name: Comment gid

on:
  pull_request:
  push:

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `
            query ($owner: String!, $name: String!, $label: String!) {
              repository(owner: $owner, name: $name) {
                issues(first: 100, labels: [$label], states: OPEN) {
                  totalCount
                  nodes {
                    number
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              label: 'root'
            }
            const result = await github.graphql(query, variables)
            console.log(result)

            for (const issue of result.repository.issues.nodes) {
              const query = `
              query ($owner: String!, $name: String!, $number: Int!) {
                repository(owner: $owner, name: $name) {
                  issue(number: $number) {
                    comments(first: 100) {
                      nodes {
                        comment
                        body
                      }
                    }
                  }
                }
              }`;

              const variables = {
                owner: context.repo.owner,
                name: context.repo.repo,
                number: issue.number
              }

              const result = await github.graphql(query, variables)
              let id = null;
              for (const comment of result.repository.issue.comments.nodes) {
                if(comment.body.include("GENERATED GID")) {
                  id = comment.id
                }
              }
              if (id !== null) {
                console.log("update comment!!")
              }
            }
