name: Comment gid

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  grasp_issue:
    runs-on: macOS-latest
    name: Grasp issue dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: k-nasa/gid@main
        with:
          label: 'root'
          github_token: ${{secrets.GITHUB_TOKEN}}
